BINDING_HEADER_AUI = "RillaUI"
BINDING_NAME_RILLAUILEAVEPARTY = "Leave Party"
BINDING_NAME_RILLAUIHIDEBARS = "Hide ActionBars OOC"
BINDING_NAME_CHECKUSERVERSION = "Check Northern Sky Weakaura Version"